version: '3.1'

services:
  db:
    build: project/containers/mssql
    restart: always
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=Mandatory@Passw0rd"
      - "MSSQL_TARGET_DATABASE=doobie-util"
    ports:
      - "65535:1433"
